services:
  django:
    image: webapp-image:latest
    container_name: webapp-container
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - app_storage:/app/storage
    environment:
      PYTHONPATH: "/app"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      DATABASE_URL: "sqlite:////app/storage/db.sqlite3"
    command: sh /app/docker_entrypoint.sh

volumes:
  app_storage:
