services:
  django:
    image: webapp-image:latest
    container_name: webapp-container
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PYTHONPATH: "${PYTHONPATH}:/app"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      DATABASE_URL: "sqlite:////db.sqlite3"
