# Generated by Django 5.1.2 on 2025-04-03 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('FAULT', 'Fault')], default='OK', max_length=10)),
                ('importance', models.IntegerField(default=0, help_text='Higher value means more important')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_repair', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Repair'}, related_name='assigned_machinery_repair', to=settings.AUTH_USER_MODEL)),
                ('assigned_technicians', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Technicians'}, related_name='assigned_machinery_tech', to=settings.AUTH_USER_MODEL)),
                ('collections', models.ManyToManyField(blank=True, related_name='machinery', to='App.collection')),
            ],
            options={
                'verbose_name_plural': 'Machinery',
                'ordering': ['-importance', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MachineryFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_faults', to=settings.AUTH_USER_MODEL)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='App.machinery')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_faults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fault_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='App.machineryfault')),
            ],
        ),
        migrations.CreateModel(
            name='FaultComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.machineryfault')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineryWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warnings', to=settings.AUTH_USER_MODEL)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='App.machinery')),
            ],
            options={
                'unique_together': {('machinery', 'text')},
            },
        ),
    ]
